### ISSUE TITLE
Cannot deploy rbac in namespace.

### ISSUE THREAD

**Issue by Tonemon** [MVDB0110/CTFd-Kubernetes#2]
Hi,

I was trying to deploy CTFd inside Kubernetes by following the ```GET STARTED``` page and it worked. After configuring CTFd I created a new challenge, set the type to ```kubedefault``` and added the string ```bmdpbng6CiAgaW1hZ2U6IG5naW54``` to the compose field. The content of this base64 encoded string is a test nginx docker-compose file:
```yml
nginx:
  image: nginx
```

After trying to start the challenge I get a **"Cannot deploy rbac in namespace"** error. I have rbac authorization enabled (checked it with ```kubectl api-versions```) and I can see that a new namespace called ```ctf-user-1-1``` is created in the Kubernetes Dashboard.  In this namespace a new secret called ```private-registry``` is created (which only contains the ```{"auths": {}}```), but after that it looks like nothing is happening until I get the error. 

How could I fix this? Also, is there a way to check plugin debug messages?

**Comment by MVDB0110** [comment]
Hi,

If you check the F12 menu and then the network traffic, you will see a errored connection. If you check the response of that connection, you will see a debugging message.

**Comment by LuXc-NL** [comment]
Hi @MVDB0110,

Could you maybe be more specific? Are you talking about the flask console? If yes, what is the F12 menu?

Edit: You meant the Browser Inspect tool. Got it.

**Comment by Tonemon** [comment]
I checked the network traffic tab in the F12 Browser inspect tool and after trying to start a challenge I got a ```409``` status response on the ```rbac``` file. 

The response I got in the browser was:
```json
{
	"role": {
		"detail": {
			"metadata": {
				"generateName": "deploy"
			}
		},
		"message": "(403)\nReason: Forbidden\nHTTP response headers: HTTPHeaderDict({'Audit-Id': '6aXXXX0a-cee8-4a7b-b306-e8XXXXX2f9', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '549467a1-2a54-4XXXX9327-3b0e8422925c', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'cf4ff84f-787c-4093-96d4-bXXXXX15a9', 'Date': 'Fri, 04 Feb 2022 12:42:18 GMT', 'Content-Length': '335'})\nHTTP response body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"serviceaccounts is forbidden: User \\\"system:serviceaccount:ctfdaemon:ctf-serviceaccount\\\" cannot create resource \\\"serviceaccounts\\\" in API group \\\"\\\" in the namespace \\\"ctf-user-1-1\\\"\",\"reason\":\"Forbidden\",\"details\":{\"kind\":\"serviceaccounts\"},\"code\":403}\n\n",
		"status": false
	},
	"secret": {
		"detail": {
			"data": {
				".dockerconfigjson": "eyJhdXRocyI6IHt9fQ=="
			},
			"metadata": {
				"name": "private-registry"
			},
			"type": "kubernetes.io/dockerconfigjson"
		},
		"message": "(409)\nReason: Conflict\nHTTP response headers: HTTPHeaderDict({'Audit-Id': 'e5XXXXc-3877-4f9b-9c94-3ZZZXXXZ082f', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '549467a1-2a54-XXXX-9327-3b0e8422925c', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'cf4ff84f-787c-XXXX-96d4-b6XXXXef15a9', 'Date': 'Fri, 04 Feb 2022 12:42:18 GMT', 'Content-Length': '216'})\nHTTP response body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"secrets \\\"private-registry\\\" already exists\",\"reason\":\"AlreadyExists\",\"details\":{\"name\":\"private-registry\",\"kind\":\"secrets\"},\"code\":409}\n\n",
		"status": false
	}
}
```
In the 'role' part of the JSON response there is a message ```serviceaccounts is forbidden: User \\\"system:serviceaccount:ctfdaemon:ctf-serviceaccount\\\" cannot create resource \\\"serviceaccounts\\\" in API group``` which makes it look like there is a permission error. I find this strange as the ```ctf-serviceaccount``` in the ```ctfd-deployment.yaml``` file has a ```ClusterRole``` to create namespaces, services, deployments, jobs, roles, rolebindings, so it shouldn't raise permission errors. 

Do you maybe know how I could fix this?

**Comment by Tonemon** [comment]
Hi, I got it working by changing the ```resources``` in the ```rules``` of the ```ClusterRole``` in the ```ctfd-deployment.yaml``` file from:
```yaml
rules:
- apiGroups: ["", "apps", "batch", "rbac.authorization.k8s.io"]
  resources: ["pods", "namespaces", "services", "deployments", "jobs", "roles", "rolebindings", "nodes", "secrets"]
  verbs: ["get", "list", "create", "update", "patch", "watch", "delete", "deletecollection"]
```

to:
```yaml
rules:
- apiGroups: ["", "apps", "batch", "rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "create", "update", "patch", "watch", "delete", "deletecollection"]
```

After changing, the RBAC functions work correctly and during the launch of a challenge result in a ```201``` status code. This however allows the ctfd ClusterRole to access too many resources. Do you maybe know which of the resources are required to make it work without giving access to all resources?

**Comment by MVDB0110** [comment]
Hi, I see that in the rbac-configuration there needs to be an entry for serviceaccount creation. This means I need to update my documentation

```
rules:
- apiGroups: ["", "apps", "batch", "rbac.authorization.k8s.io"]
  resources: ["pods", "namespaces", "services", "deployments", "jobs", "roles", "rolebindings", "nodes", "secrets", "serviceaccounts"]
  verbs: ["get", "list", "create", "update", "patch", "watch", "delete", "deletecollection"]
```
